[package]
name = "week1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
poloto = "8.0.2"
anyhow = "1.0.56"
clap = {version = "3.1.6" , features = ["derive"]}
num = "0.4.0"